export class EylemPlaniMaddeTable {
	public static eylemPlaniMaddes: any = [
		{
			id: 1,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Spor",
			eylemNo: "KEK20200101",
			eylemName:
				"Dopingle Mücadele konusunda bilgi ve tecrübe paylaşımına yönelik işbirliği sağlanması",
			eylemDescription:
				"Dopingle Mücadele konusunda bilgi ve tecrübe paylaşımına yönelik işbirliği sağlanması",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/11/2020",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 1,
		},
		{
			id: 2,
			eylemPlan: "2020-2025 Özbekistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200102",
			eylemName: "E-Ticaret/Dijital ticaret alanında işbirliği",
			eylemDescription: "E-Ticaret/Dijital ticaret alanında işbirliği",
			eylemStartDate: "01/05/2020",
			eylemEndDate: "01/11/2023",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 2,
		},
		{
			id: 3,
			eylemPlan: "2020-2025 Özbekistan Eylem Planı",
			eylemArea: "Gümrük",
			eylemNo: "KEK20200103",
			eylemName: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemDescription: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemStartDate: "01.04.2020",
			eylemEndDate: "01.04.2024",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 1,
		},
		{
			id: 4,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Spor",
			eylemNo: "KEK20200104",
			eylemName:
				"Doping Kontrol Programı geliştirme konusunda işbirliğinin sağlanması",
			eylemDescription:
				"Doping Kontrol Programı geliştirme konusunda işbirliğinin sağlanması",
			eylemStartDate: "01.04.2020",
			eylemEndDate: "01.11.2021",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 2,
		},
		{
			id: 5,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Spor",
			eylemNo: "KEK20200105",
			eylemName: "2022 Spor Müsabakalarının Gerçekleştirilmesi",
			eylemDescription: "2022 Spor Müsabakalarının Gerçekleştirilmesi",
			eylemStartDate: "01.04.2020",
			eylemEndDate: "01.11.2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 4,
		},
		{
			id: 6,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Enerji",
			eylemNo: "KEK20200106",
			eylemName:
				"Eti Maden tarafından üretilen bor ve bor ürünleri satışının Kazakistan’da arttırılması",
			eylemDescription:
				"Eti Maden tarafından üretilen bor ve bor ürünleri satışının Kazakistan’da arttırılması",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 3,
		},
		{
			id: 7,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200107",
			eylemName:
				"Türkiye-Kazakistan Ticaret ve Sanayi Odası Forumu Toplantısı ve İş Forumu yapılması",
			eylemDescription:
				"Türkiye-Kazakistan Ticaret ve Sanayi Odası Forumu Toplantısı ve İş Forumu yapılması",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 0,
		},

		{
			id: 8,
			eylemPlan: "2020-2030 Özbekistan Eylem Planı",
			eylemArea: "Gümrük",
			eylemNo: "KEK20200108",
			eylemName: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemDescription: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2025",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 4,
		},
		{
			id: 9,
			eylemPlan: "2020-2030 Özbekistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200109",
			eylemName: "Ticarette teknik engellerin kaldırılması",
			eylemDescription: "Ticarette teknik engellerin kaldırılması",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2030",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 4,
		},
		{
			id: 10,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Spor",
			eylemNo: "KEK20200110",
			eylemName: "Özbekistan spor eğitim altyapısının güçlendirilmesi",
			eylemDescription:
				"Özbekistan spor eğitim altyapısının güçlendirilmesi",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/11/2020",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 0,
		},
		{
			id: 11,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Spor",
			eylemNo: "KEK20200111",
			eylemName:
				"Yüksek Lisans eğitimi alanında ortak eğitim programları düzenlenmesi",
			eylemDescription:
				"Yüksek Lisans eğitimi alanında ortak eğitim programları düzenlenmesi",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/11/2020",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 2,
		},
		{
			id: 12,
			eylemPlan: "2020-2030 Özbekistan Eylem Planı",
			eylemArea: "Sanayi",
			eylemNo: "KEK20200112",
			eylemName:
				"Özbekistan Valilik temsilcilerine ve oda personeline eğitim verilmesi",
			eylemDescription:
				"Özbekistan Valilik temsilcilerine ve oda personeline eğitim verilmesi",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/10/2030",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 2,
		},
		{
			id: 13,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Sanayi",
			eylemNo: "KEK20200113",
			eylemName: "Kazakistan sanayicileri ile işbirliği yapılması",
			eylemDescription: "Kazakistan sanayicileri ile işbirliği yapılması",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/05/2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 3,
		},
		{
			id: 14,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Sanayi",
			eylemNo: "KEK20200114",
			eylemName:
				"Organize Sanayi Bölgeleri tüzel kişiliklerinin Kazakistan’daki muhataplarıyla birlikte organize sanayi bölgeleri kurmaları",
			eylemDescription:
				"Organize Sanayi Bölgeleri tüzel kişiliklerinin Kazakistan’daki muhataplarıyla birlikte organize sanayi bölgeleri kurmaları",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/10/2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 4,
		},

		{
			id: 15,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Milli Para",
			eylemNo: "KEK20200115",
			eylemName:
				"İki ülke arasındaki ticarette ulusal para birimlerinin kullanımının desteklenmesi",
			eylemDescription:
				"İki ülke arasındaki ticarette ulusal para birimlerinin kullanımının desteklenmesi",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2021",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 2,
		},
		{
			id: 16,
			eylemPlan: "2020-2030 Özbekistan Eylem Planı",
			eylemArea: "Sanayi",
			eylemNo: "KEK20200116",
			eylemName:
				"Özbekistan Valilik temsilcilerine ve oda personeline eğitim verilmesi",
			eylemDescription:
				"Özbekistan Valilik temsilcilerine ve oda personeline eğitim verilmesi",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2028",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Gençlik ve Spor Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 3,
		},
	];
}
