export class EylemPlaniMaddeTable {
	public static eylemPlaniMaddes: any = [
		{
			id: 1,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200101",
			eylemName: "Tercihli Ticaret Anlaşması imzalanması",
			eylemDescription: "Tercihli Ticaret Anlaşması imzalanması",
			eylemStartDate: "01/03/2020",
			eylemEndDate: "01/11/2020",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: [
				"T.C. Ticaret Bakanlığı",
				"T.C. Gençlik ve Spor Bakanlığı",
			],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 4,
		},
		{
			id: 2,
			eylemPlan: "2020-2025 Özbekistan Eylem Planı",
			eylemArea: "Milli Para",
			eylemNo: "KEK20200102",
			eylemName: "E-Ticaret/Dijital ticaret alanında işbirliği",
			eylemDescription: "E-Ticaret/Dijital ticaret alanında işbirliği",
			eylemStartDate: "01/05/2020",
			eylemEndDate: "01/11/2021",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 6,
		},
		{
			id: 3,
			eylemPlan: "2020-2025 Özbekistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200103",
			eylemName: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemDescription: "Gümrük alanında işbirliğinin geliştirilmesi",
			eylemStartDate: "01.04.2020",
			eylemEndDate: "01.04.2022",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: ["T.C. Ticaret Bakanlığı"],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 0,
		},
		{
			id: 4,
			eylemPlan: "2020-2023 Özbekistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200104",
			eylemName:
				"Doping Kontrol Programı geliştirme konusunda işbirliğinin sağlanması",
			eylemDescription:
				"Doping Kontrol Programı geliştirme konusunda işbirliğinin sağlanması",
			eylemStartDate: "01.04.2020",
			eylemEndDate: "01.11.2021",
			foreignResponsibleInstitution: [],
			localResponsibleInstitution: [
				"T.C. Ticaret Bakanlığı",
				"T.C. Gençlik ve Spor Bakanlığı",
			],
			relatedInstitution: "",
			ownerInstitution: "",
			status: 0,
		},
		{
			id: 5,
			eylemPlan: "2020-2022 Kazakistan Eylem Planı",
			eylemArea: "Ticaret",
			eylemNo: "KEK20200105",
			eylemName:
				"Eti Maden tarafından üretilen bor ve bor ürünleri satışının Özbekistan’da arttırılması",
			eylemDescription:
				"Eti Maden tarafından üretilen bor ve bor ürünleri satışının Özbekistan’da arttırılması",
			eylemStartDate: "01.03.2020",
			eylemEndDate: "31.12.2024",
			foreignResponsibleInstitution: "string[]",
			localResponsibleInstitution: "string[]",
			relatedInstitution: "",
			ownerInstitution: "",
			status: 0,
		},
	];
}
